Game console Shaped
KrystalJean/henry-game pull request #11
Opened 2022-10-18 04:56 UTC by AyushRaghuvanshi

2022-10-18 17:29 UTC, KrystalJean commented on index.html
> -        <div id="logo">
This logo should not be deleted.

2022-10-18 17:50 UTC, KrystalJean requested changes
I do not see that any changes were made to the CSS file, or any style changes.  I am wondering if you forgot to commit ALL of your changes.  Please look into this, and update this request with all of your work.

2022-10-18 17:50 UTC, KrystalJean commented on index.html
> +        <div id="game-console-top-bottom"></div>
Please, walk me through the reasoning for changing the id name here.  Is it possible that you did not commit some CSS changes that you made?

2022-10-18 17:50 UTC, KrystalJean commented on index.html
> -        </div>
This is the logo, and should not be deleted.

2022-10-18 18:01 UTC, AyushRaghuvanshi commented
I might have not commited the changes. I am closing this PR and will make another with changes.

2022-10-18 18:01 UTC, closed without merging

2022-10-22 20:27 UTC, KrystalJean commented
Are you still working on sending in your commits @AyushRaghuvanshi ?